import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ReduxProvider } from './shared/store/reduxProvider';
import { Header } from './widgets/Header/Header';
import { useAppDispatch } from './shared/store/store';
import InitApp from './init/InitApp';
import { styleText } from 'util';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['cyrillic'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased`}>
        <ReduxProvider>
          <div>
            <InitApp />
            <Header />
            <div className="wrap">
              <div className="container">{children}</div>
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
